#!/bin/bash
# Backup script for {{ .app_name }}
# Generated by Spooky

set -e

BACKUP_DIR="/backups/{{ .app_name }}"
DATE=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="${BACKUP_DIR}/backup_${DATE}.tar.gz"

echo "Creating backup for {{ .app_name }}..."

# Create backup directory
mkdir -p "${BACKUP_DIR}"

# Create database backup
pg_dump -h {{ .db_host }} -U {{ .db_user }} {{ .db_name }} > /tmp/db_backup.sql

# Create application backup
tar -czf "${BACKUP_FILE}" \
    -C /opt/{{ .app_name }} \
    config/ \
    data/ \
    logs/ \
    /tmp/db_backup.sql

# Clean up temporary files
rm -f /tmp/db_backup.sql

# Keep only last 7 days of backups
find "${BACKUP_DIR}" -name "backup_*.tar.gz" -mtime +7 -delete

echo "Backup completed: ${BACKUP_FILE}"
