#!/bin/bash
# Deployment script for {{ .app_name }}
# Generated by Spooky

set -e

echo "Deploying {{ .app_name }} version {{ .app_version }} to {{ .environment }}"

# Create necessary directories
mkdir -p /opt/{{ .app_name }}/config
mkdir -p /opt/{{ .app_name }}/logs
mkdir -p /opt/{{ .app_name }}/data

# Copy configuration files
cp config/app.conf /opt/{{ .app_name }}/config/
cp config/nginx.conf /etc/nginx/nginx.conf

# Set permissions
chown -R {{ .user }}:{{ .group }} /opt/{{ .app_name }}
chmod 755 /opt/{{ .app_name }}

# Restart services
systemctl daemon-reload
systemctl restart {{ .app_name }}
systemctl restart nginx

echo "Deployment completed successfully!"
