package commands

import (
	"fmt"
	"os"

	"spooky/internal/encryption"
	"spooky/internal/templates"

	"github.com/spf13/cobra"
)

var templateCmd = &cobra.Command{
	Use:   "template",
	Short: "Template rendering with transparent decryption",
	Long: `Template rendering with transparent decryption.

This command demonstrates how templates can be rendered with encrypted variables
being automatically decrypted during template context preparation.`,
}

var templateRenderCmd = &cobra.Command{
	Use:   "render [template-file] [output-file]",
	Short: "Render a template with transparent decryption",
	Long: `Render a template file with transparent decryption of encrypted variables.

The template renderer will automatically decrypt any encrypted variables in the
template context, making them available to templates without any special syntax.

Example:
  spooky template render templates/env.tmpl output.env`,
	Args: cobra.ExactArgs(2),
	RunE: func(cmd *cobra.Command, args []string) error {
		templateFile := args[0]
		outputFile := args[1]

		// Check if template file exists
		if _, err := os.Stat(templateFile); os.IsNotExist(err) {
			return fmt.Errorf("template file does not exist: %s", templateFile)
		}

		// Create age encryption instance (you would normally load from config)
		ageEncryption, err := encryption.NewAgeEncryption("", "")
		if err != nil {
			return fmt.Errorf("failed to create age encryption: %w", err)
		}

		// Create transparent decryptor
		transparentDecryptor := encryption.NewTransparentDecryptor(ageEncryption)

		// Create template renderer
		renderer := templates.NewTemplateRenderer(transparentDecryptor)

		// Create example template context with encrypted variables
		context := createExampleTemplateContext()

		// Render the template
		fmt.Printf("Rendering template: %s\n", templateFile)
		fmt.Printf("Output file: %s\n", outputFile)

		if err := renderer.RenderTemplateToFile(templateFile, outputFile, context); err != nil {
			return fmt.Errorf("failed to render template: %w", err)
		}

		fmt.Println("Template rendered successfully!")
		fmt.Println("Note: Encrypted variables were automatically decrypted during rendering.")

		return nil
	},
}

var templateValidateCmd = &cobra.Command{
	Use:   "validate [template-file]",
	Short: "Validate a template file",
	Long: `Validate a template file for syntax errors.

This command checks if a template file can be parsed without errors,
without actually rendering it.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		templateFile := args[0]

		// Check if template file exists
		if _, err := os.Stat(templateFile); os.IsNotExist(err) {
			return fmt.Errorf("template file does not exist: %s", templateFile)
		}

		// Create age encryption instance (not needed for validation, but required by renderer)
		ageEncryption, err := encryption.NewAgeEncryption("", "")
		if err != nil {
			return fmt.Errorf("failed to create age encryption: %w", err)
		}

		// Create transparent decryptor
		transparentDecryptor := encryption.NewTransparentDecryptor(ageEncryption)

		// Create template renderer
		renderer := templates.NewTemplateRenderer(transparentDecryptor)

		// Validate the template
		fmt.Printf("Validating template: %s\n", templateFile)

		if err := renderer.ValidateTemplate(templateFile); err != nil {
			return fmt.Errorf("template validation failed: %w", err)
		}

		fmt.Println("Template is valid!")
		return nil
	},
}

var templateDemoCmd = &cobra.Command{
	Use:   "demo",
	Short: "Demonstrate template rendering with encrypted variables",
	Long: `Demonstrate template rendering with encrypted variables.

This command creates a sample template and renders it with encrypted variables
to show how transparent decryption works.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Create a sample template
		sampleTemplate := `# Environment Variables Template
# Generated by Spooky for {{ .app_name }}

# Application
APP_NAME={{ .app_name }}
APP_VERSION={{ .app_version }}

# Database
DATABASE_URL=postgresql://{{ .db_user }}:{{ .database_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}
DB_HOST={{ .db_host }}
DB_PORT={{ .db_port }}
DB_NAME={{ .db_name }}
DB_USER={{ .db_user }}
DB_PASSWORD={{ .database_password }}

# API Keys
API_KEY={{ .api_key }}
SECRET_KEY={{ .secret_key }}

# The template writer doesn't need to know about encryption!
# All encrypted variables are automatically decrypted
`

		// Create age encryption instance
		ageEncryption, err := encryption.NewAgeEncryption("", "")
		if err != nil {
			return fmt.Errorf("failed to create age encryption: %w", err)
		}

		// Create transparent decryptor
		transparentDecryptor := encryption.NewTransparentDecryptor(ageEncryption)

		// Create template renderer
		renderer := templates.NewTemplateRenderer(transparentDecryptor)

		// Create example template context
		context := createExampleTemplateContext()

		// Render the template string
		fmt.Println("=== Template Demo ===")
		fmt.Println("Template content:")
		fmt.Println(sampleTemplate)

		rendered, err := renderer.RenderTemplateString(sampleTemplate, context)
		if err != nil {
			return fmt.Errorf("failed to render template: %w", err)
		}

		fmt.Println("Rendered output (encrypted variables automatically decrypted):")
		fmt.Println(rendered)

		return nil
	},
}

// createExampleTemplateContext creates an example template context with encrypted variables
func createExampleTemplateContext() *templates.TemplateContext {
	// Example variables with encrypted values
	variables := map[string]interface{}{
		"app_name":    "my-app",
		"app_version": "1.2.3",
		"db_host":     "localhost",
		"db_port":     5432,
		"db_name":     "mydb",
		"db_user":     "postgres",
		"database_password": map[string]interface{}{
			"encrypted_value": map[string]interface{}{
				"data":         "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcXlZUVVYK3laQWIrQktmUXFjUms4UXBubnVRRmluY2xxdjFBTnJUYmhrCklRSU1ZSzF5WUUzTk93dDZSTEVsbFN4OWx4cEQwV2hwU3pIdVlNUnNyWG8KLS0tIHIxZmppL0lhY1hNb1JmT1NuL3dSM09lTE8rT0JQcUNPUWtJZmt5Y1d0U2MKacyxJxUPuPYmKk52ru3jzcItw18rlQSJ/SZoE4QRQ1JLpOc2ypNvmlnYvfUtKo83r/xiwtYRNOVme7wW5aDbHwT+AtvF86W5x7/iS4A80UBUIj5sUycJJrbgbNLkV/GQPzaiz7GSTXiaOcvoGaIbMkICRNzWYlOUteJBwiu6B3rrJjmAY14XxajUngxX0kUL6yZ/1e0HDyuszr4NyIRQ3uD/Ky3lWZx14nBw+lt+nLfXA4psfNCbneEJYzYXj21HZQpG+sv5sSbF3TlSuOTw4iL4kf6lNMCtIQlNvxiAa2VUMSSsuD4JVFHxCsppfHH2c+XkznA+SzaDV4PsQoSDp+d/ZOpJ5sPNcpMRKE4ZS3g3Bl6St+JW6uiod5vNI94BsWz+tctn6HGspzMGcn2X7lTNG9eVzwqT/NlSYpsjh+oXjJJYyImk/LI1MfDgSGYRCKMN+9//QwUGLF1p2QrbK9YAw3g8F6LuGqHkFto9CyFqcoicM7/6D7VizVJEYAl/z3j6abM=",
				"format":       "base64",
				"algorithm":    "age",
				"version":      "v1",
				"encrypted_at": "2024-01-15T10:30:00Z",
			},
			"encrypted":   false,
			"sensitive":   true,
			"description": "Database password",
		},
		"api_key": map[string]interface{}{
			"encrypted_value": map[string]interface{}{
				"data":         "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MHJITW5OZHdKTk05VER0SGJ1cEpBOHcrVkhNbjV1bFRCdW5ZSzBWT2xFCmhDb3NiUTdSTStvL0hycjJzaXBHWW0yU3I2bmhOQlF1UU91S1VZMENVQ0kKLS0tIGxUY1pwU2FESDhVekgzYlJHenoxY2FXcE1CS1dBL3pMbTdPUko2RTNrMTQKq8Z7ntSOJDeiRlHVv6tcXTT0MW6mP6gGgoomSL4aabqv/LzwLarqAjhIPu6jrbMk+CFe",
				"format":       "base64",
				"algorithm":    "age",
				"version":      "v1",
				"encrypted_at": "2024-01-15T10:30:00Z",
			},
			"encrypted":   false,
			"sensitive":   true,
			"description": "API key for external services",
		},
		"secret_key": map[string]interface{}{
			"encrypted_value": map[string]interface{}{
				"data":         "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MHJITW5OZHdKTk05VER0SGJ1cEpBOHcrVkhNbjV1bFRCdW5ZSzBWT2xFCmhDb3NiUTdSTStvL0hycjJzaXBHWW0yU3I2bmhOQlF1UU91S1VZMENVQ0kKLS0tIGxUY1pwU2FESDhVekgzYlJHenoxY2FXcE1CS1dBL3pMbTdPUko2RTNrMTQKq8Z7ntSOJDeiRlHVv6tcXTT0MW6mP6gGgoomSL4aabqv/LzwLarqAjhIPu6jrbMk+CFe",
				"format":       "base64",
				"algorithm":    "age",
				"version":      "v1",
				"encrypted_at": "2024-01-15T10:30:00Z",
			},
			"encrypted":   false,
			"sensitive":   true,
			"description": "Secret key for application",
		},
	}

	// Example machines (empty for demo)
	machines := make(map[string]interface{})

	// Example facts (empty for demo)
	facts := make(map[string]interface{})

	// Example environment variables
	environment := map[string]string{
		"NODE_ENV": "production",
		"PATH":     "/usr/local/bin:/usr/bin:/bin",
		"HOME":     "/home/user",
	}

	// Example project metadata
	project := map[string]interface{}{
		"name":        "demo-project",
		"description": "Demo project for template rendering",
		"version":     "1.0.0",
	}

	return templates.CreateTemplateContext(variables, machines, facts, environment, project)
}

func init() {
	templateCmd.AddCommand(templateRenderCmd)
	templateCmd.AddCommand(templateValidateCmd)
	templateCmd.AddCommand(templateDemoCmd)
	RootCmd.AddCommand(templateCmd)
}
