package encryption

import (
	"fmt"
	"log"
	"strings"
	"time"
)

// DemoTransparentEncryption demonstrates the complete transparent encryption/decryption system
func DemoTransparentEncryption() {
	fmt.Println("=== Transparent Encryption/Decryption Demo ===")
	fmt.Println()

	// Create age encryption instance
	ageEncryption, err := NewAgeEncryption("", "")
	if err != nil {
		log.Fatal("Failed to create age encryption:", err)
	}

	// Create transformer and transparent decryptor
	transformer := NewTransformer(ageEncryption)
	transparentDecryptor := NewTransparentDecryptor(ageEncryption)

	// Step 1: Demonstrate variable transformation
	fmt.Println("Step 1: Variable Transformation")
	fmt.Println("--------------------------------")

	// Before transformation (unencrypted)
	unencryptedVariable := map[string]interface{}{
		"value":       "my-secret-password",
		"encrypted":   true,  // This triggers transformation
		"sensitive":   false, // Will become true automatically
		"description": "Database password",
	}

	fmt.Printf("Before transformation:\n")
	fmt.Printf("  value: %v\n", unencryptedVariable["value"])
	fmt.Printf("  encrypted: %v\n", unencryptedVariable["encrypted"])
	fmt.Printf("  sensitive: %v\n", unencryptedVariable["sensitive"])
	fmt.Printf("  encrypted_value: %v\n", unencryptedVariable["encrypted_value"])
	fmt.Println()

	// Transform to encrypted
	encryptedVariable, err := transformer.TransformVariable(unencryptedVariable)
	if err != nil {
		log.Fatal("Failed to transform variable:", err)
	}

	fmt.Printf("After transformation:\n")
	fmt.Printf("  value: %v\n", encryptedVariable["value"])
	fmt.Printf("  encrypted: %v\n", encryptedVariable["encrypted"])
	fmt.Printf("  sensitive: %v\n", encryptedVariable["sensitive"])

	if encryptedValue, exists := encryptedVariable["encrypted_value"]; exists {
		if ev, ok := encryptedValue.(map[string]interface{}); ok {
			fmt.Printf("  encrypted_value:\n")
			fmt.Printf("    data: %s...\n", truncateString(ev["data"].(string), 50))
			fmt.Printf("    format: %v\n", ev["format"])
			fmt.Printf("    algorithm: %v\n", ev["algorithm"])
			fmt.Printf("    version: %v\n", ev["version"])
			fmt.Printf("    encrypted_at: %v\n", ev["encrypted_at"])
		}
	}
	fmt.Println()

	// Step 2: Demonstrate template usage
	fmt.Println("Step 2: Template Usage")
	fmt.Println("----------------------")

	// Example template (completely opaque to encryption)
	templateExample := `# Environment Variables Template
# Generated by Spooky for {{ .app_name }}

# Database
DATABASE_URL=postgresql://{{ .db_user }}:{{ .database_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}

# API Keys
API_KEY={{ .api_key }}

# The template writer doesn't need to know about encryption!
# All encrypted variables are automatically decrypted
`

	fmt.Println("Template content:")
	fmt.Println(templateExample)

	// Step 3: Demonstrate template context preparation
	fmt.Println("Step 3: Template Context Preparation")
	fmt.Println("------------------------------------")

	// Create template context with encrypted variables
	variables := map[string]interface{}{
		"database_password": encryptedVariable,
		"app_name":          "my-app",
		"db_user":           "postgres",
		"db_host":           "localhost",
		"db_port":           5432,
		"db_name":           "mydb",
		"api_key":           "plaintext-api-key",
	}

	fmt.Println("Template context variables:")
	for key, value := range variables {
		if key == "database_password" {
			fmt.Printf("  %s: [ENCRYPTED - will be decrypted automatically]\n", key)
		} else {
			fmt.Printf("  %s: %v\n", key, value)
		}
	}
	fmt.Println()

	// Step 4: Demonstrate transparent decryption
	fmt.Println("Step 4: Transparent Decryption")
	fmt.Println("------------------------------")

	// Note: This will fail in the demo because we don't have age identities
	// In a real scenario, this would decrypt the values for template usage
	_, err = transparentDecryptor.DecryptVariable(encryptedVariable)
	if err != nil {
		fmt.Printf("Decryption would happen here (failed in demo: %v)\n", err)
		fmt.Println("In a real scenario with proper age identities, this would succeed.")
	} else {
		fmt.Println("Decryption successful!")
	}
	fmt.Println()

	// Step 5: Demonstrate structured encryption format
	fmt.Println("Step 5: Structured Encryption Format")
	fmt.Println("------------------------------------")

	structuredValue := &EncryptedValueV1{
		Data:        "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcXlZUVVYK3laQWIrQktmUXFjUms4UXBubnVRRmluY2xxdjFBTnJUYmhrCklRSU1ZSzF5WUUzTk93dDZSTEVsbFN4OWx4cEQwV2hwU3pIdVlNUnNyWG8KLS0tIHIxZmppL0lhY1hNb1JmT1NuL3dSM09lTE8rT0JQcUNPUWtJZmt5Y1d0U2MKacyxJxUPuPYmKk52ru3jzcItw18rlQSJ/SZoE4QRQ1JLpOc2ypNvmlnYvfUtKo83r/xiwtYRNOVme7wW5aDbHwT+AtvF86W5x7/iS4A80UBUIj5sUycJJrbgbNLkV/GQPzaiz7GSTXiaOcvoGaIbMkICRNzWYlOUteJBwiu6B3rrJjmAY14XxajUngxX0kUL6yZ/1e0HDyuszr4NyIRQ3uD/Ky3lWZx14nBw+lt+nLfXA4psfNCbneEJYzYXj21HZQpG+sv5sSbF3TlSuOTw4iL4kf6lNMCtIQlNvxiAa2VUMSSsuD4JVFHxCsppfHH2c+XkznA+SzaDV4PsQoSDp+d/ZOpJ5sPNcpMRKE4ZS3g3Bl6St+JW6uiod5vNI94BsWz+tctn6HGspzMGcn2X7lTNG9eVzwqT/NlSYpsjh+oXjJJYyImk/LI1MfDgSGYRCKMN+9//QwUGLF1p2QrbK9YAw3g8F6LuGqHkFto9CyFqcoicM7/6D7VizVJEYAl/z3j6abM=",
		Format:      "base64",
		Algorithm:   "age",
		Version:     "v1",
		EncryptedAt: time.Now().Format(time.RFC3339),
	}

	fmt.Printf("Structured encrypted value:\n")
	fmt.Printf("  Data: %s...\n", truncateString(structuredValue.Data, 50))
	fmt.Printf("  Format: %s\n", structuredValue.Format)
	fmt.Printf("  Algorithm: %s\n", structuredValue.Algorithm)
	fmt.Printf("  Version: %s\n", structuredValue.Version)
	fmt.Printf("  EncryptedAt: %s\n", structuredValue.EncryptedAt)

	// Verify no headers/footers in data
	if strings.Contains(structuredValue.Data, "-----BEGIN AGE ENCRYPTED FILE-----") {
		fmt.Println("  ❌ Data contains AGE headers (should not)")
	} else {
		fmt.Println("  ✅ Data does not contain AGE headers (correct)")
	}

	if strings.Contains(structuredValue.Data, "-----END AGE ENCRYPTED FILE-----") {
		fmt.Println("  ❌ Data contains AGE footers (should not)")
	} else {
		fmt.Println("  ✅ Data does not contain AGE footers (correct)")
	}
	fmt.Println()

	// Step 6: Demonstrate HCL configuration format
	fmt.Println("Step 6: HCL Configuration Format")
	fmt.Println("--------------------------------")

	fmt.Println("Example HCL configuration with structured encryption:")
	fmt.Println("```hcl")
	fmt.Println("variables {")
	fmt.Println("  variable \"database_password\" {")
	fmt.Println("    description = \"Database password\"")
	fmt.Println("    encrypted_value = {")
	fmt.Printf("      data = \"%s...\"\n", truncateString(structuredValue.Data, 50))
	fmt.Printf("      format = \"%s\"\n", structuredValue.Format)
	fmt.Printf("      algorithm = \"%s\"\n", structuredValue.Algorithm)
	fmt.Printf("      version = \"%s\"\n", structuredValue.Version)
	fmt.Printf("      encrypted_at = \"%s\"\n", structuredValue.EncryptedAt)
	fmt.Println("    }")
	fmt.Println("    encrypted = false  # No longer needed")
	fmt.Println("    sensitive = true   # Automatically set")
	fmt.Println("  }")
	fmt.Println("}")
	fmt.Println("```")
	fmt.Println()

	fmt.Println("=== Demo Complete ===")
	fmt.Println()
	fmt.Println("Key Benefits:")
	fmt.Println("1. Templates are completely opaque to encryption")
	fmt.Println("2. Automatic transformation from unencrypted to encrypted")
	fmt.Println("3. Transparent decryption during template rendering")
	fmt.Println("4. Structured encryption format with metadata")
	fmt.Println("5. No AGE headers/footers in HCL configuration")
}

// truncateString truncates a string to the specified length and adds "..."
func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}

// DemoMachineWithFacts demonstrates machine configuration with encrypted authentication
func DemoMachineWithFacts() {
	fmt.Println("=== Machine with Facts Demo ===")
	fmt.Println()

	// Create age encryption instance
	ageEncryption, err := NewAgeEncryption("", "")
	if err != nil {
		log.Fatal("Failed to create age encryption:", err)
	}

	transformer := NewTransformer(ageEncryption)

	// Example machine entry with facts
	machine := map[string]interface{}{
		"name":        "web-server-01",
		"description": "Primary web server with facts and variables",
		"hostname":    "web01.example.com",
		"port":        22,
		"user":        "admin",
		"authentication": map[string]interface{}{
			"method":          "publickey",
			"public_key_path": "~/.ssh/id_rsa",
			"passphrase": map[string]interface{}{
				"value":     "my-ssh-passphrase",
				"encrypted": true, // This triggers transformation
			},
		},
		"connection_timeout": 30,
		"max_retries":        3,
		"retry_delay":        5,
		"facts": map[string]interface{}{
			"os_family":    "linux",
			"os_version":   "Ubuntu 22.04.3 LTS",
			"architecture": "x86_64",
			"hostname":     "web01.example.com",
			"domain":       "example.com",
			"location":     "us-east-1",
			"environment":  "production",
			"role":         "web-server",
		},
		"variables": map[string]interface{}{
			"app_port": map[string]interface{}{
				"value":       8080,
				"description": "Application port",
			},
			"api_key": map[string]interface{}{
				"value":       "secret-api-key",
				"encrypted":   true, // This triggers transformation
				"description": "API key for external services",
			},
		},
	}

	fmt.Printf("Machine: %s\n", machine["name"])
	fmt.Printf("Hostname: %s\n", machine["hostname"])
	fmt.Printf("OS: %s %s\n",
		machine["facts"].(map[string]interface{})["os_family"],
		machine["facts"].(map[string]interface{})["os_version"])
	fmt.Printf("Architecture: %s\n", machine["facts"].(map[string]interface{})["architecture"])
	fmt.Printf("Environment: %s\n", machine["facts"].(map[string]interface{})["environment"])
	fmt.Printf("Role: %s\n", machine["facts"].(map[string]interface{})["role"])

	// Transform encrypted values
	auth := machine["authentication"].(map[string]interface{})
	passphrase := auth["passphrase"].(map[string]interface{})
	encryptedPassphrase, err := transformer.TransformVariable(passphrase)
	if err != nil {
		log.Fatal("Failed to transform passphrase:", err)
	}
	auth["passphrase"] = encryptedPassphrase

	variables := machine["variables"].(map[string]interface{})
	apiKey := variables["api_key"].(map[string]interface{})
	encryptedAPIKey, err := transformer.TransformVariable(apiKey)
	if err != nil {
		log.Fatal("Failed to transform API key:", err)
	}
	variables["api_key"] = encryptedAPIKey

	// Show that authentication passphrase is encrypted
	if ev, ok := encryptedPassphrase["encrypted_value"].(map[string]interface{}); ok {
		fmt.Printf("SSH Passphrase: [ENCRYPTED - %s]\n", ev["algorithm"])
	}

	// Show machine variables
	fmt.Printf("App Port: %v\n", variables["app_port"].(map[string]interface{})["value"])
	if ev, ok := encryptedAPIKey["encrypted_value"].(map[string]interface{}); ok {
		fmt.Printf("API Key: [ENCRYPTED - %s]\n", ev["algorithm"])
	}

	fmt.Println()
	fmt.Println("=== Machine Demo Complete ===")
}

// DemoFactEncryption demonstrates fact encryption using the same pattern as variables
func DemoFactEncryption() {
	fmt.Println("=== Fact Encryption Demo ===")
	fmt.Println()

	// Create age encryption instance
	ageEncryption, err := NewAgeEncryption("", "")
	if err != nil {
		log.Fatal("Failed to create age encryption:", err)
	}

	// Create transformer and transparent decryptor
	transformer := NewTransformer(ageEncryption)
	transparentDecryptor := NewTransparentDecryptor(ageEncryption)

	// Step 1: Demonstrate fact transformation
	fmt.Println("Step 1: Fact Transformation")
	fmt.Println("----------------------------")

	// Before transformation (unencrypted fact)
	unencryptedFact := map[string]interface{}{
		"value":       "sensitive-api-key-12345",
		"type":        "string",
		"description": "API key for external service",
		"encrypted":   true,  // This triggers transformation
		"sensitive":   false, // Will become true automatically
		"tags":        []string{"api", "external"},
	}

	fmt.Printf("Before transformation:\n")
	fmt.Printf("  value: %v\n", unencryptedFact["value"])
	fmt.Printf("  type: %v\n", unencryptedFact["type"])
	fmt.Printf("  encrypted: %v\n", unencryptedFact["encrypted"])
	fmt.Printf("  sensitive: %v\n", unencryptedFact["sensitive"])
	fmt.Printf("  encrypted_value: %v\n", unencryptedFact["encrypted_value"])
	fmt.Println()

	// Transform to encrypted (using the same transformer as variables)
	encryptedFact, err := transformer.TransformVariable(unencryptedFact)
	if err != nil {
		log.Fatal("Failed to transform fact:", err)
	}

	fmt.Printf("After transformation:\n")
	fmt.Printf("  value: %v\n", encryptedFact["value"])
	fmt.Printf("  type: %v\n", encryptedFact["type"])
	fmt.Printf("  encrypted: %v\n", encryptedFact["encrypted"])
	fmt.Printf("  sensitive: %v\n", encryptedFact["sensitive"])

	if encryptedValue, exists := encryptedFact["encrypted_value"]; exists {
		if ev, ok := encryptedValue.(map[string]interface{}); ok {
			fmt.Printf("  encrypted_value:\n")
			fmt.Printf("    data: %s...\n", truncateString(ev["data"].(string), 50))
			fmt.Printf("    format: %v\n", ev["format"])
			fmt.Printf("    algorithm: %v\n", ev["algorithm"])
			fmt.Printf("    version: %v\n", ev["version"])
			fmt.Printf("    encrypted_at: %v\n", ev["encrypted_at"])
		}
	}
	fmt.Println()

	// Step 2: Demonstrate template usage with facts
	fmt.Println("Step 2: Template Usage with Facts")
	fmt.Println("----------------------------------")

	// Example template using facts
	templateExample := `# Application Configuration
# Generated by Spooky for {{ .app_name }}

# Database connection using facts
DATABASE_URL=postgresql://{{ .db_user }}:{{ .database_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}

# API configuration using facts
API_KEY={{ .api_key }}
API_ENDPOINT={{ .api_endpoint }}

# The template writer doesn't need to know about encryption!
# All encrypted facts are automatically decrypted
`

	fmt.Println("Template content:")
	fmt.Println(templateExample)

	// Step 3: Demonstrate template context preparation with facts
	fmt.Println("Step 3: Template Context Preparation with Facts")
	fmt.Println("------------------------------------------------")

	// Create template context with encrypted facts
	facts := map[string]interface{}{
		"api_key":           encryptedFact,
		"app_name":          "my-app",
		"db_user":           "postgres",
		"db_host":           "localhost",
		"db_port":           5432,
		"db_name":           "mydb",
		"database_password": "plaintext-password",
		"api_endpoint":      "https://api.example.com",
	}

	fmt.Println("Template context facts:")
	for key, value := range facts {
		if key == "api_key" {
			fmt.Printf("  %s: [ENCRYPTED - will be decrypted automatically]\n", key)
		} else {
			fmt.Printf("  %s: %v\n", key, value)
		}
	}
	fmt.Println()

	// Step 4: Demonstrate transparent decryption of facts
	fmt.Println("Step 4: Transparent Decryption of Facts")
	fmt.Println("----------------------------------------")

	// Decrypt the fact using the same transparent decryptor
	decryptedFact, err := transparentDecryptor.DecryptVariable(encryptedFact)
	if err != nil {
		log.Fatal("Failed to decrypt fact:", err)
	}

	fmt.Printf("Decrypted fact value: %s\n", decryptedFact)
	fmt.Println()

	// Step 5: Show HCL representation
	fmt.Println("Step 5: HCL Representation")
	fmt.Println("---------------------------")

	fmt.Println("Original HCL (before encryption):")
	fmt.Println("  fact \"api_key\" {")
	fmt.Println("    value = \"sensitive-api-key-12345\"")
	fmt.Println("    type = \"string\"")
	fmt.Println("    description = \"API key for external service\"")
	fmt.Println("    encrypted = true")
	fmt.Println("    tags = [\"api\", \"external\"]")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("Transformed HCL (after encryption):")
	fmt.Println("  fact \"api_key\" {")
	fmt.Println("    value = \"sensitive-api-key-12345\"")
	fmt.Println("    type = \"string\"")
	fmt.Println("    description = \"API key for external service\"")
	fmt.Println("    sensitive = true")
	fmt.Println("    tags = [\"api\", \"external\"]")
	fmt.Println("    encrypted_value = {")
	if ev, ok := encryptedFact["encrypted_value"].(map[string]interface{}); ok {
		fmt.Printf("      data = \"%s\"\n", ev["data"])
		fmt.Printf("      format = \"%s\"\n", ev["format"])
		fmt.Printf("      algorithm = \"%s\"\n", ev["algorithm"])
		fmt.Printf("      version = \"%s\"\n", ev["version"])
		fmt.Printf("      encrypted_at = \"%s\"\n", ev["encrypted_at"])
	}
	fmt.Println("    }")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("=== Fact Encryption Demo Complete ===")
}
