package encryption

import (
	"fmt"
	"log"
)

// ExampleTransparentDecryption demonstrates how the transparent decryption system works
func ExampleTransparentDecryption() {
	// This is an example showing how the transparent decryption system works
	// In a real implementation, you would load age identities and recipients

	// Example 1: Simple variable transformation
	fmt.Println("=== Example 1: Variable Transformation ===")

	// Before transformation (unencrypted)
	unencryptedVariable := map[string]interface{}{
		"value":       "my-secret-password",
		"encrypted":   true,  // This triggers transformation
		"sensitive":   false, // Will become true automatically
		"description": "Database password",
	}

	fmt.Printf("Before transformation: %+v\n", unencryptedVariable)

	// After transformation (encrypted)
	encryptedVariable := map[string]interface{}{
		"encrypted_value": map[string]interface{}{
			"data":         "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcXlZUVVYK3laQWIrQktmUXFjUms4UXBubnVRRmluY2xxdjFBTnJUYmhrCklRSU1ZSzF5WUUzTk93dDZSTEVsbFN4OWx4cEQwV2hwU3pIdVlNUnNyWG8KLS0tIHIxZmppL0lhY1hNb1JmT1NuL3dSM09lTE8rT0JQcUNPUWtJZmt5Y1d0U2MKacyxJxUPuPYmKk52ru3jzcItw18rlQSJ/SZoE4QRQ1JLpOc2ypNvmlnYvfUtKo83r/xiwtYRNOVme7wW5aDbHwT+AtvF86W5x7/iS4A80UBUIj5sUycJJrbgbNLkV/GQPzaiz7GSTXiaOcvoGaIbMkICRNzWYlOUteJBwiu6B3rrJjmAY14XxajUngxX0kUL6yZ/1e0HDyuszr4NyIRQ3uD/Ky3lWZx14nBw+lt+nLfXA4psfNCbneEJYzYXj21HZQpG+sv5sSbF3TlSuOTw4iL4kf6lNMCtIQlNvxiAa2VUMSSsuD4JVFHxCsppfHH2c+XkznA+SzaDV4PsQoSDp+d/ZOpJ5sPNcpMRKE4ZS3g3Bl6St+JW6uiod5vNI94BsWz+tctn6HGspzMGcn2X7lTNG9eVzwqT/NlSYpsjh+oXjJJYyImk/LI1MfDgSGYRCKMN+9//QwUGLF1p2QrbK9YAw3g8F6LuGqHkFto9CyFqcoicM7/6D7VizVJEYAl/z3j6abM=",
			"format":       "base64",
			"algorithm":    "age",
			"version":      "v1",
			"encrypted_at": "2024-01-15T10:30:00Z",
		},
		"encrypted":   false, // No longer needed
		"sensitive":   true,  // Automatically set because encrypted_value exists
		"description": "Database password",
	}

	fmt.Printf("After transformation: %+v\n", encryptedVariable)

	// Example 2: Template usage remains the same
	fmt.Println("\n=== Example 2: Template Usage ===")

	// Template context preparation (this happens transparently)
	variables := map[string]interface{}{
		"database_password": encryptedVariable,
		"app_name":          "my-app",
		"db_host":           "localhost",
	}

	fmt.Println("Template context variables:")
	for key, value := range variables {
		if key == "database_password" {
			fmt.Printf("  %s: [ENCRYPTED - will be decrypted transparently]\n", key)
		} else {
			fmt.Printf("  %s: %v\n", key, value)
		}
	}

	// Example 3: Template usage (completely opaque to encryption)
	fmt.Println("\n=== Example 3: Template Usage ===")

	templateExample := `
# Environment Variables Template
# Generated by Spooky for {{ .app_name }}

# Database
DATABASE_URL=postgresql://user:{{ .database_password }}@{{ .db_host }}:5432/mydb
DB_PASSWORD={{ .database_password }}

# The template writer doesn't need to know about encryption!
# {{ .database_password }} will be automatically decrypted
`

	fmt.Println("Template content:")
	fmt.Println(templateExample)

	fmt.Println("Rendered output (after transparent decryption):")
	fmt.Println("# Environment Variables Template")
	fmt.Println("# Generated by Spooky for my-app")
	fmt.Println("")
	fmt.Println("# Database")
	fmt.Println("DATABASE_URL=postgresql://user:my-secret-password@localhost:5432/mydb")
	fmt.Println("DB_PASSWORD=my-secret-password")
	fmt.Println("")
	fmt.Println("# The template writer doesn't need to know about encryption!")
	fmt.Println("# database_password was automatically decrypted")
}

// ExampleMachineWithFacts demonstrates a machine entry with facts
func ExampleMachineWithFacts() {
	fmt.Println("\n=== Example Machine with Facts ===")

	// Example machine entry with facts
	machine := map[string]interface{}{
		"name":        "web-server-01",
		"description": "Primary web server with facts",
		"hostname":    "web01.example.com",
		"port":        22,
		"user":        "admin",
		"authentication": map[string]interface{}{
			"method":          "publickey",
			"public_key_path": "~/.ssh/id_rsa",
			"passphrase": map[string]interface{}{
				"encrypted_value": map[string]interface{}{
					"data":         "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcXlZUVVYK3laQWIrQktmUXFjUms4UXBubnVRRmluY2xxdjFBTnJUYmhrCklRSU1ZSzF5WUUzTk93dDZSTEVsbFN4OWx4cEQwV2hwU3pIdVlNUnNyWG8KLS0tIHIxZmppL0lhY1hNb1JmT1NuL3dSM09lTE8rT0JQcUNPUWtJZmt5Y1d0U2MKacyxJxUPuPYmKk52ru3jzcItw18rlQSJ/SZoE4QRQ1JLpOc2ypNvmlnYvfUtKo83r/xiwtYRNOVme7wW5aDbHwT+AtvF86W5x7/iS4A80UBUIj5sUycJJrbgbNLkV/GQPzaiz7GSTXiaOcvoGaIbMkICRNzWYlOUteJBwiu6B3rrJjmAY14XxajUngxX0kUL6yZ/1e0HDyuszr4NyIRQ3uD/Ky3lWZx14nBw+lt+nLfXA4psfNCbneEJYzYXj21HZQpG+sv5sSbF3TlSuOTw4iL4kf6lNMCtIQlNvxiAa2VUMSSsuD4JVFHxCsppfHH2c+XkznA+SzaDV4PsQoSDp+d/ZOpJ5sPNcpMRKE4ZS3g3Bl6St+JW6uiod5vNI94BsWz+tctn6HGspzMGcn2X7lTNG9eVzwqT/NlSYpsjh+oXjJJYyImk/LI1MfDgSGYRCKMN+9//QwUGLF1p2QrbK9YAw3g8F6LuGqHkFto9CyFqcoicM7/6D7VizVJEYAl/z3j6abM=",
					"format":       "base64",
					"algorithm":    "age",
					"version":      "v1",
					"encrypted_at": "2024-01-15T10:30:00Z",
				},
				"encrypted": false,
				"sensitive": true,
			},
		},
		"connection_timeout": 30,
		"max_retries":        3,
		"retry_delay":        5,
		"facts": map[string]interface{}{
			"os_family":    "linux",
			"os_version":   "Ubuntu 22.04.3 LTS",
			"architecture": "x86_64",
			"hostname":     "web01.example.com",
			"domain":       "example.com",
			"location":     "us-east-1",
			"environment":  "production",
			"role":         "web-server",
		},
		"variables": map[string]interface{}{
			"app_port": map[string]interface{}{
				"value":       8080,
				"encrypted":   false,
				"sensitive":   false,
				"description": "Application port",
			},
			"api_key": map[string]interface{}{
				"encrypted_value": map[string]interface{}{
					"data":         "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MHJITW5OZHdKTk05VER0SGJ1cEpBOHcrVkhNbjV1bFRCdW5ZSzBWT2xFCmhDb3NiUTdSTStvL0hycjJzaXBHWW0yU3I2bmhOQlF1UU91S1VZMENVQ0kKLS0tIGxUY1pwU2FESDhVekgzYlJHenoxY2FXcE1CS1dBL3pMbTdPUko2RTNrMTQKq8Z7ntSOJDeiRlHVv6tcXTT0MW6mP6gGgoomSL4aabqv/LzwLarqAjhIPu6jrbMk+CFe",
					"format":       "base64",
					"algorithm":    "age",
					"version":      "v1",
					"encrypted_at": "2024-01-15T10:30:00Z",
				},
				"encrypted":   false,
				"sensitive":   true,
				"description": "API key for external services",
			},
		},
	}

	fmt.Printf("Machine: %s\n", machine["name"])
	fmt.Printf("Hostname: %s\n", machine["hostname"])
	fmt.Printf("OS: %s %s\n",
		machine["facts"].(map[string]interface{})["os_family"],
		machine["facts"].(map[string]interface{})["os_version"])
	fmt.Printf("Architecture: %s\n", machine["facts"].(map[string]interface{})["architecture"])
	fmt.Printf("Environment: %s\n", machine["facts"].(map[string]interface{})["environment"])
	fmt.Printf("Role: %s\n", machine["facts"].(map[string]interface{})["role"])

	// Show that authentication passphrase is encrypted
	auth := machine["authentication"].(map[string]interface{})
	passphrase := auth["passphrase"].(map[string]interface{})
	fmt.Printf("SSH Passphrase: [ENCRYPTED - %s]\n",
		passphrase["encrypted_value"].(map[string]interface{})["algorithm"])

	// Show machine variables
	variables := machine["variables"].(map[string]interface{})
	fmt.Printf("App Port: %v\n", variables["app_port"].(map[string]interface{})["value"])
	fmt.Printf("API Key: [ENCRYPTED - %s]\n",
		variables["api_key"].(map[string]interface{})["encrypted_value"].(map[string]interface{})["algorithm"])
}

func Example() {
	ExampleTransparentDecryption()
	ExampleMachineWithFacts()

	log.Println("Examples completed successfully!")
}
