name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Install golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run golangci-lint
      run: |
        golangci-lint run --timeout=5m

    - name: Check code formatting
      run: |
        # Check formatting for all Go files
        UNFORMATTED_FILES=$(gofmt -s -l . 2>/dev/null || true)
        
        if [ -n "$UNFORMATTED_FILES" ]; then
          echo "Code is not formatted. Please run 'gofmt -s -w .'"
          echo "Unformatted files: $UNFORMATTED_FILES"
          exit 1
        fi

    - name: Check for unused dependencies
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go.mod or go.sum has uncommitted changes. Please run 'go mod tidy'"
          git status
          exit 1
        fi 