name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Run unit tests
      run: |
        go test ./... -v -race -coverprofile=coverage.out

    - name: Check if coverage file exists
      if: always()
      run: |
        if [ -f "coverage.out" ]; then
          echo "Coverage file exists, size: $(wc -c < coverage.out) bytes"
          echo "Coverage report:"
          go tool cover -func=coverage.out | tail -1
        else
          echo "No coverage file generated"
        fi

    - name: Verify build works
      run: |
        go build -o /tmp/spooky-test main.go
        echo "Build verification successful" 